# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        source-url: https://nuget.pkg.github.com/BargainMagic/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build -c Release --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Pack
      run: dotnet pack --no-build --verbosity normal

    - name: Publish
      run: dotnet nuget push "*.nupkg" -k ${ secrets.GITHUB_TOKEN }} -s "https://nuget.pkg.github.com/BargainMagic/index.json"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
